source 'https://rubygems.org'

gem 'rails', '~> 8.0', '>= 8.0.0'

group :development, :test do
  gem 'debug'
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'erb_lint', require: false
end

group :test do
  gem 'rubocop-rspec', require: false
  gem 'rubocop-rspec_rails', require: false
end
