source 'https://rubygems.org'

group :development, :test do
  gem 'debug'
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-rspec_rails', require: false
  gem 'erb_lint', require: false
end
